# Generated by Django 3.1 on 2020-09-23 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(max_length=20, null=True, verbose_name='Género')),
                ('ciudad', models.CharField(max_length=126, null=True, verbose_name='Ciudad')),
                ('empleo', models.CharField(max_length=126, null=True, verbose_name='Empleo')),
                ('enfermedades', models.CharField(max_length=126, null=True, verbose_name='Enfermedades')),
                ('isopado', models.BooleanField(null=True, verbose_name='Isopado')),
                ('fecha_isopado', models.DateTimeField(null=True, verbose_name='Fecha de isopado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_permiso', models.CharField(choices=[('caminata', 'Caminata'), ('compras', 'Compras'), ('mudanza', 'Mudanza'), ('visitaMedica', 'Visita medica'), ('viaje', 'Viaje')], max_length=15)),
                ('estado', models.CharField(choices=[('sinAdmin', 'Permiso solicitado'), ('conAdmin', 'Permiso en revision'), ('aprobado', 'Permiso aprobado'), ('rechazado', 'Permiso rechazado')], default='sinAdmin', max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=256, null=True)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
                ('administrador_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OtroGrupo.ciudadano')),
            ],
        ),
    ]
