# Generated by Django 3.1.1 on 2020-09-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtroGrupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtroGrupo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateTimeField(blank=True)),
                ('ciudad', models.CharField(max_length=126)),
                ('empleo', models.CharField(max_length=126)),
                ('enfermedades', models.CharField(max_length=126)),
                ('isopado', models.BooleanField()),
                ('fechaIsopado', models.DateTimeField(blank=True, null=True)),
                ('dniId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtroGrupo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoPermiso', models.CharField(choices=[('caminata', 'Caminata'), ('compras', 'Compras'), ('mudanza', 'Mudanza'), ('visitaMedica', 'Visita medica'), ('viaje', 'Viaje')], max_length=15)),
                ('estado', models.CharField(choices=[('sinAdmin', 'Permiso solicitado'), ('conAdmin', 'Permiso en revision'), ('aprobado', 'Permiso aprobado'), ('rechazado', 'Permiso rechazado')], default='sinAdmin', max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=256, null=True)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
                ('administradorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='OtroGrupo.administrador')),
                ('ciudadanoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtroGrupo.ciudadano')),
            ],
        ),
    ]
